changes to Chinese Codification
zbateson/mb-wrapper pull request #3
Opened 2020-09-02 11:18 UTC by jorgedelacalle

This changes repair problems with some characters in GB2312 codification using GB18030.

2020-09-03 09:49 UTC, mrCartmenez requested changes

2020-09-03 09:49 UTC, mrCartmenez commented on src/MbWrapper.php
> +        'GB2312' => 'GB18030',
This change provides a supported encoding, so can move down in the list.

2020-09-03 09:49 UTC, mrCartmenez commented
GB18030 is supported in PHP and backwards compatible with GB2312.
https://www.iana.org/assignments/charset-reg/GB18030

2021-11-06 01:57 UTC, merged

2021-11-06 01:58 UTC, zbateson commented
Sorry, didn't notice your pull request before today.  Thanks for this.